# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.define "vserver" do |vserver|
    vserver.vm.box = "centos/7"
    vserver.vm.hostname = "vaultserver"
    vserver.vm.network "private_network", ip: "192.13.16.31"
    vserver.vm.network :forwarded_port, guest: 8200, host: 8200
    vserver.vm.network :forwarded_port, guest: 8201, host: 8201
    #vserver.vm.network "public_network", ip: "192.168.0.17"
    vserver.vm.provision "shell", path: "bootstrap.sh"
    #vserver.vm.provision "shell", inline: <<-SHELL
    #  sudo yum install -y yum-utils
    #  sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
    #  sudo yum -y install vault
    #  sudo yum -y install net-tools
    #  sudo yum install -y bind-utils
    #  sudo yum install -y epel-release
    #  sudo yum install -y jq
   #SHELL
  end

#  config.vm.define "vclient" do |vclient|
#    vclient.vm.box="centos/7"
#    vclient.vm.hostname = "vaultclient"
#    vclient.vm.network "private_network", ip: "10.0.16.32"
#    vclient.vm.network "public_network", ip: "192.168.0.18"
#    vclient.vm.network "forwarded_port", guest: 80, host: 8080
#    vclient.vm.provision "shell", inline: <<-SHELL
#      sudo yum install -y yum-utils
#      sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
#      sudo yum -y install vault
#      sudo yum -y install net-tools
#      sudo yum install -y epel-release
#      sudo yum install -y jq
#      sudo yum install -y bind-utils
#    SHELL
#  end
 
end
